# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](text)\
[](overlay1)\
$os\
$username\
[](bg:overlay0 fg:overlay1)\
$directory\
[](fg:overlay0 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface0)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:surface0 bg:base)\
$docker_context\
$conda\
[](fg:base bg:crust)\
$time\
[](fg:crust)\
$line_break$character"""

palette = "catppuccin_mocha"
#palette = "gruvbox_dark"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.gruvbox_dark]
mauve = "#b16286"
red = "#cc241d"
green = '#98971a'
text = "#fbf1c7"
subtext0 = "#83a598"
overlay1 = "#d65d0e"
overlay0 = "#d79921"
surface1 = "#689d6a"
surface0 = "#458588"
base = "#665c54"
crust = "#3c3836"

[palettes.pastel_powerline]
mauve = "#b16286"
red = "#cc241d"
green = '#98971a'
text = "#fbf1c7"
subtext0 = "#83a598"
overlay1 = "#9a348e"
overlay0 = "#da627d"
surface1 = "#fca17d"
surface0 = "#86bbd8"
base = "#33658a"
crust = "#33658a"

[os]
disabled = false
style = "bg:overlay1 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:overlay1 fg:text"
style_root = "bg:overlay1 fg:text"
format = '[ $user ]($style)'

[directory]
style = "bg:overlay0 fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = "󰋜"
".config" = ""
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $branch ](fg:text bg:surface1)]($style)'

[git_status]
style = "bg:surface1"
format = '[[($all_status$ahead_behind )](fg:text bg:surface1)]($style)'

[nodejs]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[c]
symbol = " "
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[rust]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[golang]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[php]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[java]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[kotlin]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[haskell]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[python]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:text bg:surface0)]($style)'

[docker_context]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $context) ](fg:subtext0 bg:base)]($style)'

[conda]
style = "bg:base"
format = '[[ $symbol( $environment) ](fg:subtext0 bg:base)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:crust"
format = '[[  $time ](fg:text bg:crust)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[╰─](fg: text) [❯❯](bold fg:green)'
error_symbol = '[╰─](fg: text) [❯❯](bold fg:red)'
vimcmd_symbol = '[╰─](fg: text) [❮❮](bold fg:green)'
vimcmd_replace_one_symbol = '[╰─](fg: text) [❮❮](bold fg:mauve)'
vimcmd_replace_symbol = '[╰─](fg: text) [❮❮](bold fg:mauve)'
vimcmd_visual_symbol = '[╰─](fg: text) [❮❮](bold fg:overlay0)'
